### ISSUE TITLE
Template "@Var:" is not defined

### ISSUE THREAD

**Issue by mahagr** [finanalyst/grav-plugin-map-marker-leaflet#21] opened 2020-09-02 13:43 UTC
Can be replicated if using bad shortcode:

```
[map-leaflet lat=51.505 lng=-0.09 zoom=13 mapname=neighbourhood variant=neighbourhood scale ]
[a-markers markerColor="darkblue"
iconColor="white"
]
[a-markers markerColor="beige" iconColor="darkpurple"]
```

**Comment by finanalyst** [comment] 2020-12-22 14:42
It's not really possible to allow for all possibility of bad shortcodes. If replicates with a good shortcode, then I can see what the problem is. Otherwise, I'm closing this issue. Thanks for the attention, sorry for the delay in responding

**Closed as completed by finanalyst** 2020-12-22 14:42 UTC
